#Package installation in termux 
$ apt update && apt upgrade 
$ pkg install python 
$ pkg install git 
$ git clone https://github.com/ulinNha/B43sCrack 
$ pip install requests bs4 python3 
$ pip install mechanize
